-- DROP
-- DATABASE IF EXISTS test;

-- CREATE
-- DATABASE `test` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

-- USE
-- `test`

CREATE TABLE `user`
(
    `id`         BIGINT      NOT NULL AUTO_INCREMENT COMMENT '유저 ID',
    `name`       VARCHAR(30) NOT NULL COMMENT '이름',
    `email`      VARCHAR(30) NOT NULL COMMENT '이메일',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '생성 시각',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 시각',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT '유저';
