/* eslint-disable */

/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/

/** 유저 */
export interface User {
  
  /** 생성 시각 */
  'created_at'?: Date | null;
  
  /** 이메일 */
  'email': string;
  
  /** 유저 ID */
  'id'?: string;
  
  /** 이름 */
  'name': string;
  
  /** 수정 시각 */
  'updated_at'?: Date | null;
}
